language: node_js
node_js:
  - 10

branches:
  only:
  - master

before_install:
  - npm i -g npm@6.4.1

script:
  - npm run lint
  - npm run dist
  - npm run test

addons:
  chrome: stable

cache:
  directories:
    - node_modules
  npm: true
